# Generated by Django 5.1.2 on 2024-10-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('ile_kalorii', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('calories_per_100g', models.FloatField()),
                ('proteins_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fats_per_100g', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('activity_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.CreateModel(
            name='Posilek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('kcal', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('przepis', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posilki', to='plans.plan')),
            ],
        ),
        migrations.CreateModel(
            name='SkładPosiłku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_produktu', models.CharField(max_length=255)),
                ('typ', models.CharField(max_length=50)),
                ('ilosc', models.FloatField()),
                ('jednostka', models.CharField(max_length=20)),
                ('posiłek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skladniki', to='plans.posilek')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posilki', to='plans.produkt')),
            ],
        ),
    ]
