# Generated by Django 5.1.2 on 2024-10-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkładPosiłku',
            new_name='SkladPosilku',
        ),
        migrations.RenameField(
            model_name='skladposilku',
            old_name='posiłek',
            new_name='posilek',
        ),
    ]
