# Generated by Django 5.1.2 on 2024-10-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_rename_składposiłku_skladposilku_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produkt',
            new_name='Product',
        ),
    ]
